config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: 'publics/registrations',
    sessions: 'publics/sessions',
    omniauth_callbacks: 'publics/omniauth_callbacks',
    passwords: 'publics/passwords',
  }

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'publics/sessions#new_guest'
  end

  scope module: :publics do
    root 'homes#top'
    get 'oahu' => 'abouts#oahu', as: 'oahu'
    get 'kauai' => 'abouts#kauai', as: 'kauai'
    get 'molokai' => 'abouts#molokai', as: 'molokai'
    get 'maui' => 'abouts#maui', as: 'maui'
    get 'lanai' => 'abouts#lanai', as: 'lanai'
    get 'hawaii' => 'abouts#hawaii', as: 'hawaii'
    get 'question' => 'categorys#question', as: 'question'
    get 'sns' => 'categorys#sns', as: 'sns'
    get 'youtube' => 'categorys#youtube', as: 'youtube'
    get 'reference_links' => 'categorys#reference_links', as: 'reference_links' # 参考資料
    patch "/customers/withdraw" => "customers#withdraw", as: 'withdraw' # 退会ステータス用
    get 'inquiry' => 'inquiry#index', as: 'inquiry' # お問い合わせ
    post 'confirm' => 'inquiry#confirm', as: 'confirm'
    post 'thanks'  => 'inquiry#thanks', as: 'thanks'
    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'searchs#search'
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admins do
    get 'top' => 'homes#top', as: 'top'
    resources :admins, only: [:edit, :update, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admin!
  layout "admins/header"

  def index
    if @posts = params[:created_at]
      today_posts = Date.today.beginning_of_day..Date.today.end_of_day
      post = Post.where(created_at: today_posts)
      posts = post.all
    else
      posts = Post.all
    end
    @posts = posts.page(params[:page]).per(10).reverse_order
  end
  
  def show
    @post = Post.find(params[:id])
    # @customer = Customer.find(params[:id])
    @genres = Genre.all
    @customer = @post.customer
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # 値がnilの場合は左側
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
  end 

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      @posts = Post.all.page(params[:page]).per(10).reverse_order
      redirect_to admins_posts_path, notice: "投稿を変更しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      @posts = Post.all.page(params[:page]).per(10).reverse_order
      redirect_to admins_posts_path, notice: "投稿を削除しました。"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :explanation, :image, :genre_id, :customer_id)
  end
end

app/controllers/publics/abouts_controller.rb
class Publics::AboutsController < ApplicationController
  before_action :authenticate_customer!
  layout "publics/header"

  def oahu
  end

  def kauai
  end

  def molokai
  end

  def maui
  end

  def lanai
  end

  def hawaii
  end
end

app/controllers/publics/categorys_controller.rb
class Publics::CategorysController < ApplicationController
  before_action :authenticate_customer!, only: [:question, :sns, :youtube]
  layout "publics/header"

  def question # Q&A
  end

  def sns
  end

  def youtube
  end

  def reference_links # 参考資料
  end
end

app/controllers/publics/comments_controller.rb
class Publics::CommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_customer.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.customer_id = current_customer.id
    @comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:edit, :update]
  layout "publics/header"

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(12).reverse_order
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer == Customer.find_by(email: "guest@guest.com") # ゲストユーザーの場合
      redirect_to customer_path(@customer), alert: "ゲストユーザーのため退会や変更はお控えください。"
    elsif @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def withdraw # 退会用アクション
    @customer = current_customer
    if @customer == Customer.find_by(email: "guest@guest.com") # ゲストユーザーの場合
      redirect_to edit_customer_path(@customer), alert: "ゲストユーザーのため退会や変更はお控えください。"
    else
      @customer.update(is_deleted: "退会済み")
      reset_session
      redirect_to root_path, alert: "退会しました。"
    end 
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image, :birthday, :country, :visit_time)
  end

  def ensure_correct_customer # 会員権限
    customer = Customer.find(params[:id])
    if current_customer != customer
      redirect_to customer_path(current_customer.id)
    end
  end
end

app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < ApplicationController # いいね機能
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    unless @post.favorited_by?(current_customer)
      favorite = @post.favorites.new(customer_id: current_customer.id)
      favorite.save
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    if @post.favorited_by?(current_customer)
      favorite = current_customer.favorites.find_by(post_id: @post.id)
      favorite.destroy
    end
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  layout "publics/homes-header"

  def top
    @posts = Post.all.page(params[:page]).per(9).reverse_order
    @customer = current_customer
    @genres = Genre.all
  end
end

app/controllers/publics/inquiry_controller.rb
class Publics::InquiryController < ApplicationController # お問い合わせ用
  before_action :authenticate_customer!
  layout "publics/header"

  def index # フォーム入力画面
    @inquiry = Inquiry.new
    render :index
  end

  def confirm # 確認画面
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      render :confirm # OK。確認画面を表示
    else
      render :index # NG。入力画面を再表示
    end
  end

  def thanks # サンクスページ
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # SNS認証
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env["omniauth.auth"]
    info = Customer.find_oauth(@omniauth)
    @customer = info[:customer]
    if @customer.persisted?
      sign_in_and_redirect @customer, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "publics/registrations/new", alert: "SNSでEmailが登録されていないので新しく新規登録してください"
    end
  end

  def failure
    redirect_to(root_path) && return
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  layout "publics/header"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:edit, :update, :destroy]
  layout "publics/header"

  def new
    @post = Post.new
    @post.build_spot
  end

  def index
    @posts = Post.all.page(params[:page]).per(9).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @genres = Genre.all
    @comment = Comment.new
    @customer = @post.customer
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # 値がnilの場合は左側
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @customer = @post.customer
    if @post.save
      tags = Vision.get_image_data(@post.image)    
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to post_path(@post), notice: "投稿しました！！"
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @genres = Genre.all
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # nilの場合は左側
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
  end

  def update
    @post = Post.find(params[:id])
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # nilの場合は左
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を変更しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path, alert: "投稿を削除しました。"
    end 
  end

  private

  def post_params
    params.require(:post).permit(:title, :explanation, :image, :genre_id, :customer_id, spot_attributes: [:address])
  end

  def ensure_correct_customer # 会員権限
    post = Post.find(params[:id])
    if current_customer != post.customer
      redirect_to post_path(post)
    end
  end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  layout "publics/header"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: :destroy

  def check_guest # ゲストログイン機能
    if resource.email == 'guest@guest.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/relationships_controller.rb
class Publics::RelationshipsController < ApplicationController
  layout "publics/header"

  def create
    @customer = Customer.find(params[:customer_id])
    current_customer.follow(@customer.id)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    current_customer.unfollow!(@customer)
  end

  def followings # フォロー一覧
    @customer = Customer.find(params[:customer_id])
    @customers = @customer.followings
  end

  def followers # フォロワー一覧
    @customer = Customer.find(params[:customer_id])
    @customers = @customer.followers
  end
end

app/controllers/publics/searchs_controller.rb
class Publics::SearchsController < ApplicationController
  before_action :authenticate_customer!
  layout "publics/header"

  def search # 検索機能
    @customer_or_post = params[:option]
    @how_search = params[:choice]
    if @customer_or_post == "1"
      @customers = Customer.search(params[:search], @customer_or_post, @how_search).page(params[:page]).per(10).reverse_order
    else
      @posts = Post.search(params[:search], @customer_or_post, @how_search).page(params[:page]).per(12).reverse_order
    end
  end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]
  layout "publics/header"
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest # ゲストログイン機能
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if @customer.valid_password?(params[:customer][:encrypted_password]) && (@customer.active_for_authentication? == "退会済み")
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください"
    end
  end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/publics/posts/_index.html.erb
<div class="container">
  <div class="share-your-pic-main">
    <h1 id="share-your-pic-main">Share Your Pic On Here!!</h1>
    <div class="posts-index">
      <% posts.each do |post| %>
      <div class="post">
        <div>
          <%= link_to post_path(post) do %>
            <%= attachment_image_tag post, :image, class: "img", fallback: "no-image.png", size:"300x300" %>
          <% end %>
        </div>
        <div class="post-title">
          <%= post.title %>
        </div>
        <% if customer_signed_in? %>
          <div id="post_<%= post.id %>" style="display: inline-block;">
            <%= render "publics/favorites/favorite-btn", post: post %>
          </div>
          <%= link_to customer_path(post.customer) do %>
            <div class="user-icon">
              <i class="fas fa-user"></i>
            </div>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/publics/posts/edit.html.erb
<% @page_title = "投稿編集" %>
<div class="container">
  <div class="edit-posts">
    <h2>投稿の編集</h2>
    <div class="row">
      <%= form_with model: @post, local: true do |f| %>
        <div class="col-xs-5">
          <div class="preview_image">
    		    <%= attachment_image_tag @post, :image, class: "img", fallback: "no-image.png", size:"400x300" %>
      		</div>
        </div>
  
        <div class="col-xs-7">
          <%= render "layouts/errors", obj: @post %>
          
          <dt>タイトル</dt>
          <dd><%= f.text_field :title, class: "form-control" %></dd>
  
          <dt>説明</dt>
          <dd><%= f.text_area :explanation, class: "form-control" %></dd>
  
          <dt>ジャンル</dt>
          <dd><%= f.collection_select(:genre_id, Genre.all, :id, :name, {prompt: "選択してください"}, class: "form-control") %></dd>
          
          <dd>
            <%= f.fields_for :spot do |spot| %>
              <%= spot.label :address, "レビュー場所(Google Mapで検索)", class: "spot_title" %>
              <%= spot.text_field :address, placeholder: "スポットを入力(任意)", id: "address", class: "spot_text" %>
              <%= spot.submit "検索する", class: "search_button", onclick: "codeAddress()", type: "button" %>
            <% end %>
          </dd>
          <div class="edit_map">
            <div id="edit_map"></div>
          </div>
  
          <div class="edit-posts-btn"><%= f.submit "変更を保存", class: "btn btn-success btn-lg" %></div>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/publics/posts/index.html.erb
<% @page_title = "投稿一覧" %>
<div class="container">
<h2>投稿一覧</h2>
  <%= render "publics/posts/index", posts: @posts, post: @post %>
  <div class="paginate">
    <%= paginate @posts %>
  </div>
</div>

app/views/publics/posts/new.html.erb
<% @page_title = "新規投稿" %>
<div class="container">
  <div class="new-posts">
    <h2>ハワイの魅力を投稿しよう！</h2>
    <div class="row">
      <%= form_with model: @post, local: true, multipart: true do |f| %>
        <div class="col-xs-5">
          <div class="preview_image">
    		    <%= attachment_image_tag @post, :image, class: "image", fallback: "no-image.png", size:"400x300" %>
    				<%= f.attachment_field :image %>
      		</div>
        </div>
  
        <div class="col-xs-7">
          <%= render "layouts/errors", obj: @post %>
          
          <dt>タイトル</dt>
          <dd><%= f.text_field :title, class: "form-control", placeholder: "50文字以内" %></dd>
  
          <dt>説明</dt>
          <dd><%= f.text_area :explanation, class: "form-control", placeholder: "300文字以内" %></dd>
  
          <dt>ジャンル</dt>
          <dd><%= f.collection_select(:genre_id, Genre.all, :id, :name, {prompt: "選択してください"}, class: "form-control") %></dd>
  
          <dd>
            <%= f.fields_for :spot do |spot| %>
              <%= spot.label :address, "レビュー場所(Google Mapで検索)", class: "spot_title" %>
              <%= spot.text_field :address, placeholder: "スポットを入力(任意)", id: "address", class: "spot_text" %>
              <%= spot.submit "検索する", onclick: "codeAddress()", type: "button" %>
            <% end %>
          </dd>
          <div id="map"></div>
  
          <div class="new-posts-btn"><%= f.submit "新規投稿する", class: "btn btn-success btn-lg" %></div>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/publics/posts/show.html.erb
<% @page_title = "投稿詳細" %>
<div class="container">
  <h2>投稿詳細</h2>
  <div class="row">
    
    <div class="col-xs-7">
		  <%= attachment_image_tag @post, :image, class: "img", fallback: "no-image.png", size:"600x500" %>
    </div>

    <div class="col-xs-5">
      <div class="post-show-info">
        
        <dt>投稿者</dt>
        <dd><%= link_to @customer.name, customer_path(@post.customer) %>　さん</dd>
  
        <dt>タイトル</dt>
        <dd><%= @post.title %></dd>
  
        <dt>説明</dt>
        <dd><%= Rinku.auto_link(@post.explanation, :all, 'target="_blank"').html_safe %></dd>
  
        <dt>ジャンル</dt>
        <dd><%= @post.genre.name %></dd>
        
        <dt>いいね</dt>
        <dd>
          <div class="favorite-btn">
            <div class="post-show-favorite">
            <% if @post.favorited_by?(current_customer) %>
  	          <li>
  	            <%= link_to post_favorites_path(@post), method: :delete, remote: true do %>
  	              <%= image_tag "shaka.jpg", class: "shaka-btn" %>
                <% end %>
      	        <div class="favorite-count">
      		        <%= @post.favorites.count %>
    	          </div>
  	          </li>
            <% else %>
  	          <li>
    	          <%= link_to post_favorites_path(@post), method: :post, remote: true do %>
    	            <%= image_tag "shaka-black.jpg", class: "shaka-btn" %>
   		          <% end %>
   	  	        <div class="favorite-count">
   		            <%= @post.favorites.count %>
   		          </div>
  	          </li>
            <% end %>
            </div>
          </div>
        </dd>
        
        <div class="show-spot">
          <%= form_with model: @post, local: true, multipart: true do |f| %>
            <%= f.fields_for :spot do |spot| %>
              <%= spot.label :address, "レビュー場所(Google Mapで検索)", class: "spot_title" %>
              <%= spot.text_field :address, placeholder: "スポットを入力", id: "address", class: "spot_text" %>
              <%= spot.submit "検索する", class: "search_button", onclick: "codeAddress()", type: "button" %>
            <% end %>
          <% end %>
        </div>
        <% if @post.spot.address.present? %>
          <dt>位置情報名</dt>
          <dd><%= @post.spot.address %></dd>
          <div id="show_map"></div>
        <% end %>
  
        <% if @customer == current_customer %>
          <%= link_to "投稿を編集する", edit_post_path(@post), class: "btn btn-success" %>
          <%= link_to "投稿を削除する", post_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        <% end %>

      </div>
    </div>
  </div>

  <div class="posts-show-comment">
    <div class="post_comment">
      <%= render "publics/comments/comment", customer: @customer, post: @post, comment: @comment %>
    </div>
    <div class="error-comment">
      <%= render "layouts/errors", obj: @customer %>
    </div>
    <%= form_with model:[@post, @comment] do |f| %>
      <%= f.text_area :comment, size:"50x2", placeholder: "200文字以内" %>
      <%= f.submit "コメントをする", class: "btn btn-info" %>
    <% end %>
  </div>
</div>