config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: 'publics/registrations',
    sessions: 'publics/sessions',
    omniauth_callbacks: 'publics/omniauth_callbacks',
    passwords: 'publics/passwords',
  }

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'publics/sessions#new_guest'
  end

  scope module: :publics do
    root 'homes#top'
    get 'oahu' => 'abouts#oahu', as: 'oahu'
    get 'kauai' => 'abouts#kauai', as: 'kauai'
    get 'molokai' => 'abouts#molokai', as: 'molokai'
    get 'maui' => 'abouts#maui', as: 'maui'
    get 'lanai' => 'abouts#lanai', as: 'lanai'
    get 'hawaii' => 'abouts#hawaii', as: 'hawaii'
    get 'question' => 'categorys#question', as: 'question'
    get 'sns' => 'categorys#sns', as: 'sns'
    get 'youtube' => 'categorys#youtube', as: 'youtube'
    get 'reference_links' => 'categorys#reference_links', as: 'reference_links' # 参考資料
    patch "/customers/withdraw" => "customers#withdraw", as: 'withdraw' # 退会ステータス用
    get 'inquiry' => 'inquiry#index', as: 'inquiry' # お問い合わせ
    post 'confirm' => 'inquiry#confirm', as: 'confirm'
    post 'thanks'  => 'inquiry#thanks', as: 'thanks'
    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'searchs#search'
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admins do
    get 'top' => 'homes#top', as: 'top'
    resources :admins, only: [:edit, :update, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!
  layout "admins/header"

  def top
    today_posts = Date.today.beginning_of_day..Date.today.end_of_day
    @posts = Post.where(created_at: today_posts)
  end
end

app/controllers/publics/abouts_controller.rb
class Publics::AboutsController < ApplicationController
  before_action :authenticate_customer!
  layout "publics/header"

  def oahu
  end

  def kauai
  end

  def molokai
  end

  def maui
  end

  def lanai
  end

  def hawaii
  end
end

app/controllers/publics/categorys_controller.rb
class Publics::CategorysController < ApplicationController
  before_action :authenticate_customer!, only: [:question, :sns, :youtube]
  layout "publics/header"

  def question # Q&A
  end

  def sns
  end

  def youtube
  end

  def reference_links # 参考資料
  end
end

app/controllers/publics/comments_controller.rb
class Publics::CommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_customer.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.customer_id = current_customer.id
    @comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:edit, :update]
  layout "publics/header"

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(12).reverse_order
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = Customer.find(current_customer.id)
    if @customer == Customer.find_by(email: "guest@guest.com") # ゲストユーザーの場合
      redirect_to customer_path(@customer), alert: "ゲストユーザーのため退会や変更はお控えください。"
    elsif @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def withdraw # 退会用アクション
    @customer = current_customer
    if @customer == Customer.find_by(email: "guest@guest.com") # ゲストユーザーの場合
      redirect_to edit_customer_path(@customer), alert: "ゲストユーザーのため退会や変更はお控えください。"
    else
      @customer.update(is_deleted: "退会済み")
      reset_session
      redirect_to root_path, alert: "退会しました。"
    end 
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image, :birthday, :country, :visit_time)
  end

  def ensure_correct_customer # 会員権限
    customer = Customer.find(params[:id])
    if current_customer != customer
      redirect_to customer_path(current_customer.id)
    end
  end
end

app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < ApplicationController # いいね機能
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_id])
    unless @post.favorited_by?(current_customer)
      favorite = @post.favorites.new(customer_id: current_customer.id)
      favorite.save
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    if @post.favorited_by?(current_customer)
      favorite = current_customer.favorites.find_by(post_id: @post.id)
      favorite.destroy
    end
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  layout "publics/homes-header"

  def top
    @posts = Post.all.page(params[:page]).per(9).reverse_order
    @customer = current_customer
    @genres = Genre.all
  end
end

app/controllers/publics/inquiry_controller.rb
class Publics::InquiryController < ApplicationController # お問い合わせ用
  before_action :authenticate_customer!
  layout "publics/header"

  def index # フォーム入力画面
    @inquiry = Inquiry.new
    render :index
  end

  def confirm # 確認画面
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      render :confirm # OK。確認画面を表示
    else
      render :index # NG。入力画面を再表示
    end
  end

  def thanks # サンクスページ
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
  end
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # SNS認証
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env["omniauth.auth"]
    info = Customer.find_oauth(@omniauth)
    @customer = info[:customer]
    if @customer.persisted?
      sign_in_and_redirect @customer, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "publics/registrations/new", alert: "SNSでEmailが登録されていないので新しく新規登録してください"
    end
  end

  def failure
    redirect_to(root_path) && return
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  layout "publics/header"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:edit, :update, :destroy]
  layout "publics/header"

  def new
    @post = Post.new
    @post.build_spot
  end

  def index
    @posts = Post.all.page(params[:page]).per(9).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @genres = Genre.all
    @comment = Comment.new
    @customer = @post.customer
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # 値がnilの場合は左側
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    @customer = @post.customer
    if @post.save
      tags = Vision.get_image_data(@post.image)    
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to post_path(@post), notice: "投稿しました！！"
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @genres = Genre.all
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # nilの場合は左側
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
  end

  def update
    @post = Post.find(params[:id])
    @lat = @post.spot.nil?  ? nil :  @post.spot.latitude # nilの場合は左
    @lng = @post.spot.nil?  ? nil :  @post.spot.longitude
    gon.lat = @lat # @latと@lngの変数をJavaScriptでも扱えるように、それぞれgon.latとgon.lngに代入
    gon.lng = @lng
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を変更しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path, alert: "投稿を削除しました。"
    end 
  end

  private

  def post_params
    params.require(:post).permit(:title, :explanation, :image, :genre_id, :customer_id, spot_attributes: [:address])
  end

  def ensure_correct_customer # 会員権限
    post = Post.find(params[:id])
    if current_customer != post.customer
      redirect_to post_path(post)
    end
  end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  layout "publics/header"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: :destroy

  def check_guest # ゲストログイン機能
    if resource.email == 'guest@guest.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/relationships_controller.rb
class Publics::RelationshipsController < ApplicationController
  layout "publics/header"

  def create
    @customer = Customer.find(params[:customer_id])
    current_customer.follow(@customer.id)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    current_customer.unfollow!(@customer)
  end

  def followings # フォロー一覧
    @customer = Customer.find(params[:customer_id])
    @customers = @customer.followings
  end

  def followers # フォロワー一覧
    @customer = Customer.find(params[:customer_id])
    @customers = @customer.followers
  end
end

app/controllers/publics/searchs_controller.rb
class Publics::SearchsController < ApplicationController
  before_action :authenticate_customer!
  layout "publics/header"

  def search # 検索機能
    @customer_or_post = params[:option]
    @how_search = params[:choice]
    if @customer_or_post == "1"
      @customers = Customer.search(params[:search], @customer_or_post, @how_search).page(params[:page]).per(10).reverse_order
    else
      @posts = Post.search(params[:search], @customer_or_post, @how_search).page(params[:page]).per(12).reverse_order
    end
  end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]
  layout "publics/header"
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest # ゲストログイン機能
    customer = Customer.guest
    sign_in customer
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if @customer.valid_password?(params[:customer][:encrypted_password]) && (@customer.active_for_authentication? == "退会済み")
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください"
    end
  end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/publics/homes/reference_links.html.erb
<div class="container">
  <div class="reference_links">
    <h2>参考資料</h2>
    <div class="reference_links-list">
      <div class="reference_link">
      <p>・ALOHA PROGRAM</p>
      <%= link_to "https://www.aloha-program.com/" %>
      </div>
      <div class="reference_link">
      <p>・ハワイ州観光局</p>
      <%= link_to "https://www.gohawaii.jp/" %>
      </div>
      </div>
  </div>
</div>

app/views/publics/homes/top.html.erb
<% @page_title = "Top" %>
<%= video_tag "Go to Hawaii.mp4", autoplay: true, muted: true, loop: true, playsinline: true, style: "width:100%; height:100%;" %>

<div class="container">
  <div class="about">
    <h1 id="about">About</h1>
    <div class="imgBox">
      <%= image_tag "island.png", usemap: "#Map" %>
      <div class="about-background">
        <div class="about-logo">Hawaiian Island</div>
        <div class="KAUAI">≺KAUAI</div>
        <div class="OAHU">OAHU≻</div>
        <div class="MOLOKAI">≺MOLOKAI</div>
        <div class="MAUI">≺MAUI</div>
        <div class="LANAI">LANAI≻</div>
        <div class="HAWAII">≺HAWAII</div>
        <div class="about-title">Welcome to <strong>Go to Hawaii</strong></div>
        <div class="about-message">
          このサイトは、会員登録したユーザー様同士でハワイの情報や魅力を投稿、共有するためのサイトです。<br>
          まだハワイに行ったことない人や、もうハワイへ何度も行った人にもこのサイトを通じて情報や魅力を共有し合いハワイをより知ることができます！<br>
          また、現地で役立つ基礎知識などのコンテンツもあり、ユーザー様にとって便利なサイトとなっております！
        </div>
        <% unless customer_signed_in? %>
          <div class="about-registrations">新規登録してみる＝＞　<%= link_to "新規登録", new_customer_registration_path%></div>
        <% end %>
      </div>
      <map name="Map">
        <area shape="poly" coords="236,186,275,202,294,188,292,177,299,164,291,155,264,153,241,162,234,171,236,186,236,187" href="/kauai" alt="" />
        <area shape="poly" coords="404,226,426,225,443,211,450,212,489,263,478,270,461,273,452,264,428,267,421,254,410,243,410,236,410,236" href="/oahu" alt="" />
        <area shape="poly" coords="523,265,555,270,560,266,566,272,595,273,587,287,572,292,548,287,518,284,519,278,525,273,525,273" href="/molokai" alt="" />
        <area shape="poly" coords="546,303,548,311,556,314,557,326,576,325,582,314,570,302,570,302" href="/lanai" alt="" />
        <area shape="poly" coords="599,289,606,289,615,294,619,304,640,298,648,299,657,308,678,317,678,330,659,339,650,337,641,344,627,343,621,337,620,326,618,320,611,321,595,311,592,304,593,298,593,298" href="/maui" alt="" />
        <area shape="poly" coords="683,374,686,393,693,404,692,408,682,421,678,421,667,430,667,441,671,447,676,449,686,481,683,499,689,517,701,520,713,530,730,513,732,507,755,495,761,489,770,492,796,481,817,464,816,456,800,447,792,434,789,432,782,433,784,421,766,403,726,387,725,390,716,381,694,373,694,373" href="/hawaii" alt="" />
      </map>
    </div>
  </div>
</div>

<div class="container">
  <div class="pick-up-category">
    <h1 id="pick-up-category">Pick Up Category</h1>
    <div class="swiper">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          
          <div class="swiper-slide">
            <%= link_to question_path do %>
              <%= image_tag "frangipani.jpg", class: "swiper-images", size:"250x250" %><p>Q & A</p>
            <% end %>
          </div>
          
          <div class="swiper-slide">
            <%= link_to sns_path do %>
              <%= image_tag "pineapples.jpg", size:"250x250" %><p>SNS</p>
            <% end %>
          </div>
          
          <div class="swiper-slide">
            <%= link_to youtube_path do %>
              <%= image_tag "waikiki.jpg", class: "swiper-images", size:"250x250" %><p>Youtube</p>
            <% end %>
          </div>
          
          <div class="swiper-slide">
            <%= link_to "https://www.hawaiianairlines.co.jp/" do %>
              <%= image_tag "airplane.jpg", class: "swiper-images", size:"250x250" %><p>Book</p>
            <% end %>
          </div>
          
        </div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%= render 'publics/posts/index', posts: @posts, post: @post%>
  <% if customer_signed_in? %>
    <div class="to_new_post">
      <%= link_to "投稿する", new_post_path, class: "btn btn-info btn-lg btn-block" %>
    </div>
    <%= link_to "投稿をもっと見る⇒", posts_path, class: "to_posts-btn" %>
  <% end %>
</div>