config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: 'publics/registrations',
    sessions: 'publics/sessions',
    omniauth_callbacks: 'publics/omniauth_callbacks',
    passwords: 'publics/passwords',
  }

  devise_scope :customer do
    post 'customers/guest_sign_in' => 'publics/sessions#new_guest'
  end

  scope module: :publics do
    root 'homes#top'
    get 'oahu' => 'abouts#oahu', as: 'oahu'
    get 'kauai' => 'abouts#kauai', as: 'kauai'
    get 'molokai' => 'abouts#molokai', as: 'molokai'
    get 'maui' => 'abouts#maui', as: 'maui'
    get 'lanai' => 'abouts#lanai', as: 'lanai'
    get 'hawaii' => 'abouts#hawaii', as: 'hawaii'
    get 'question' => 'categorys#question', as: 'question'
    get 'sns' => 'categorys#sns', as: 'sns'
    get 'youtube' => 'categorys#youtube', as: 'youtube'
    get 'reference_links' => 'categorys#reference_links', as: 'reference_links' # 参考資料
    patch "/customers/withdraw" => "customers#withdraw", as: 'withdraw' # 退会ステータス用
    get 'inquiry' => 'inquiry#index', as: 'inquiry' # お問い合わせ
    post 'confirm' => 'inquiry#confirm', as: 'confirm'
    post 'thanks'  => 'inquiry#thanks', as: 'thanks'
    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'searchs#search'
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_scope :admin do
    post 'admins/guest_sign_in' => 'admins/sessions#new_guest'
  end

  namespace :admins do
    get 'top' => 'homes#top', as: 'top'
    resources :admins, only: [:edit, :update, :destroy]
    resources :customers, only: [:index, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email, presence: true

  def self.guest
    find_or_create_by!(email: "admin@guest.com") do |admin|
      admin.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true
  validates :comment, length: { maximum: 200 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i(facebook google_oauth2)

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy

  attachment :profile_image

  validates :name, { presence: true, length: { maximum: 20 } }
  validates :email, presence: true

  # マッチング機能
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def following?(customer_id)
    followings.include?(customer_id)
  end

  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end

  def unfollow!(customer_id)
    relationships.find_by(followed_id: customer_id).destroy # find_byによって1レコードを特定し、destroyメソッドで削除している。
  end

  # 検索機能
  def Customer.search(search, customer_or_post, how_search)
    if customer_or_post == "1"
      if how_search == "1"
        Customer.where(["name LIKE ?", "%#{search}%"])
      else
        Customer.all
      end
    end
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: "ゲストユーザー", email: "guest@guest.com") do |customer|
      customer.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  # SNS認証
  def self.without_sns_data(auth)
    customer = Customer.where(email: auth.info.email).first
    if customer.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        customer_id: customer.id
      )
    else
      customer = Customer.new(
        name: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { customer: customer, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    customer = Customer.where(id: snscredential.customer_id).first
    if customer.blank?
      customer = Customer.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    { customer: customer }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      customer = with_sns_data(auth, snscredential)[:customer]
      sns = snscredential
    else
      customer = without_sns_data(auth)[:customer]
      sns = without_sns_data(auth)[:sns]
    end
    { customer: customer, sns: sns }
  end
  
  # 退会機能
  def active_for_authentication?
    super && (is_deleted == "有効") # is_deletedがfalse(有効)の場合はログイン可能
  end

  enum country: {
    日本: 0,
    ハワイ: 1,
    アメリカ本土: 2,
    その他の国: 3,
  }

  enum visit_time: {
    なし: 0,
    １～３回: 1,
    ４～６回: 2,
    ６回以上: 3,
  }

  enum is_deleted: {
    有効: false,
    退会済み: true,
  }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => "を入力してください" }
  validates :email, :presence => { :message => "を入力してください" }
  validates :message, :presence => { :message => "を入力してください" }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :genre
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :spot, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :spot

  attachment :image

  validates :title, { presence: true, length: { maximum: 30 } }
  validates :explanation, { presence: true, length: { maximum: 300 } }
  validates :image, presence: true

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  # 検索機能
  def Post.search(search, customer_or_post, how_search)
    if customer_or_post == "2"
      if how_search == "1"
        Post.where(["title LIKE ?", "%#{search}%"])
      else
        Post.all
      end
    end
  end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :customer
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post

  geocoded_by :address
  after_validation :geocode
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categotys_helper.rb
module CategotysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admins/admins/edit.html.erb
<% @page_title = "管理者編集(メールアドレス)" %>
<div class="container">
  <div class="edit-admin">
    <h2>管理者編集(メールアドレス)</h2>
    <div class="edit-admin-form">
      <%= form_with model: @admin, url: admins_admin_path(@admin), method: :patch, class: "form", local: true do |f| %>
        <%= render "layouts/errors", obj: @admin %>
      
        <dt>メールアドレス</dt>
        <dd><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "registations-under" %></dd>

        <div class="edit-admin-btn">
          <%= f.submit "編集する", class: "btn btn-success btn-lg" %>
        </div>

        <dd><%= link_to "パスワードの変更はこちらから", edit_admin_registration_path(current_admin), class: "btn btn-success" %></dd>

      <% end %>
    </div>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/admins/header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "logo.jpg" %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e35fc03a93.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <title><%= page_title %></title>
  </head>
  <body>
    <header>
      <div class="admins-header">
        <nav>
          <% if admin_signed_in? %>
            <%= link_to root_path, style: "text-decoration:none" do %>
              <%= image_tag "logo.jpg", class: "header-logo" %>
            <% end %>
            <%= link_to "Top", admins_top_path, class: "header-tab" %>
            <%= link_to "Genre", admins_genres_path, class: "header-tab" %>
            <%= link_to "Customers", admins_customers_path, class: "header-tab" %>
            <%= link_to "Posts", admins_posts_path, class: "header-tab" %>
            <%= link_to "My Page", edit_admins_admin_path(current_admin), class: "header-tab" %>
            <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "header-tab" %>
          <% else %>
            <%= link_to root_path, style: "text-decoration:none" do %>
              <%= image_tag "logo.jpg", class: "header-logo" %>
            <% end %>
            <%= link_to "管理者側ログイン", new_admin_session_path, class: "header-tab" %>
            <%= link_to "会員側ログイン", new_customer_session_path, class: "header-tab" %>
          <% end %>
        </nav>
      </div>
    </header>
    <div class="background-img">
      <div class="container-lg">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "flash flash__#{key}") %><% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>